# Project information
site_name: DISCOVER Documentation
site_description: 'Symbolic Regression for Science'
site_author: 'Uday Gajera, Mohsen Sotoudeh'

# Repository
repo_url: https://github.com/u-gajera/discover
repo_name: 'discover'

# Theme configuration
theme:
  name: material
  logo: assets/discover_logo_1.png 
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

# Navigation structure
nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'tutorial.md'
  - 'How-To Guides': 'howto.md'
  - 'Contributing': 'contribution.md'
  - 'Fundamentals': 'fundamentals.md'

# Markdown extensions for rendering math and advanced formatting
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true